version: 2
jobs:
  build:
    docker:
      - image: hemeroc/jdk9
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Download Dependencies
          command: ./mvnw clean dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Integration Test
          command: ./mvnw integration-test
      - store_artifacts:
          path: ./testfx-result/


